FROM python:3.11-rc-alpine

# RUN mkdir -p /var/docker-example

# WORKDIR /var/docker-example

# COPY ./ /var/docker-example

# ENTRYPOINT python /var/docker-example/main.py

COPY . /app

ENTRYPOINT python /app/src/hello.py